version: "3.8"

services:
  frontend:
    container_name: oraculo_frontend
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app/
      - node_modules_frontend:/app/node_modules

volumes:
  node_modules_frontend:
