name: SonarCloud Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  pre-release:
    name: Pre release
    runs-on: ubuntu-latest
  
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
    
      - name: Check Repo
        uses: actions/checkout@v2
      
      - run: mkdir -p /tmp/sonar/
      - run: curl --location --request POST 'https://sonarcloud.io/api/measures/component_tree?component=fga-eps-mds_2021-1-PC-GO-Frontend&metricKeys=files,functions,complexity,comment_lines_density,duplicated_lines_density,coverage,ncloc,security_rating,tests,test_success_density,test_execution_time,reliability_rating&ps=500' > /tmp/sonar/fga-eps-mds_2021-1-PC-GO-Frontend-${{ steps.date.outputs.date }}.json
      - uses: actions/upload-artifact@v2
        with:
          name: fga-eps-mds_2021-1-PC-GO-Frontend-${{ steps.date.outputs.date }}.json
          path: /tmp/sonar/fga-eps-mds_2021-1-PC-GO-Frontend-${{ steps.date.outputs.date }}.json
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            /tmp/sonar/fga-eps-mds_2021-1-PC-GO-Frontend-${{ steps.date.outputs.date }}.json
          
      - name: Create Env file .env
        run: touch .env

      - name: Tests check
        run: sudo docker-compose run oraculo-frontend bash -c  "yarn && yarn test --coverage --watchAll=false"

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
